### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by denismosolov** [CyberLight/M101-Blog#14]
denis@denis-home:~/javascript$ git clone https://github.com/CyberLight/M101-Blog.git
Cloning into 'M101-Blog'...
remote: Counting objects: 353, done.
remote: Compressing objects: 100% (281/281), done.
remote: Total 353 (delta 189), reused 202 (delta 41)
Receiving objects: 100% (353/353), 149.45 KiB | 157 KiB/s, done.
Resolving deltas: 100% (189/189), done.
denis@denis-home:~/javascript$ ls
counter  counter2  GET  M101-Blog  visitorscounter
denis@denis-home:~/javascript$ cd M101-Blog/
denis@denis-home:~/javascript/M101-Blog$ ls
app.js  package.json  README.md  run-tests.bat  views
lib     public        routes     tests
denis@denis-home:~/javascript/M101-Blog$ node app.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/denis/javascript/M101-Blog/app.js:6:15)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)

**Comment by CyberLight** [comment]
**denismosolov** before running `node app.js` command, you must execute command `npm install` firstly  for downloading dependencies. I will add this moment to README.md. Thank you!
